=== nimile/Distributed-Systems-Tasks/data/socket/client/config.dtd
<!ELEMENT configuration (chatMessageFormat*, connection, user*)>
<!--
$dir$ [$date$ $time$] [$nick$]: $message$
-->
<!ELEMENT chatMessageFormat (#PCDATA)>
<!ELEMENT connection (networkTypes, server, ip, serverPort, timeout*, shutdownTime*, cleanerInterval*)>
<!--
Server IP: 192.168.2.104
Broadcast IP: 192.168.2.255
Multicast IP: 224.1.1.1
-->
<!ELEMENT networkTypes (#PCDATA)>
<!ELEMENT server (#PCDATA)>
<!ELEMENT ip (#PCDATA)>
<!ELEMENT serverPort (#PCDATA)>
<!ELEMENT timeout (#PCDATA)>
<!ELEMENT shutdownTime (#PCDATA)>
<!ELEMENT cleanerInterval (#PCDATA)>
<!ELEMENT user (nick, uid)>
<!ELEMENT nick (#PCDATA)>
<!ELEMENT uid (#PCDATA)>

=== nimile/Distributed-Systems-Tasks/data/socket/server/config.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE configuration SYSTEM "config.dtd">
<configuration>
    <chatMessageFormat>$dir$ [$date$ $time$] [$nick$]: $message$</chatMessageFormat>
    <connection>
        <networkTypes>SOCKET</networkTypes>
        <server>true</server>
        <ip>192.168.2.104</ip>
        <serverPort>9292</serverPort>
    </connection>
    <user>
        <nick>Server User</nick>
        <uid>7a88108c-9596-4676-b4f1-bb941418bd9a</uid>
    </user>
</configuration>
